DEBUG    twister_harness.device.factory:factory.py:37 Get device type "hardware"
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff839006e0>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffff838ccb90> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff83710910>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'188'), (b'access-control-expose-headers', b'Content-Range'), (b'content-range', b'projects 0-1/1'), (b'grpc-metadata-access-control-expose-headers', b'Content-Range'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Thu, 16 Oct 2025 00:39:20 GMT'), (b'x-kong-upstream-latency', b'17'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff83712350>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffff838cd0a0> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff838b9ba0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'287'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Thu, 16 Oct 2025 00:39:20 GMT'), (b'x-kong-upstream-latency', b'17'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: POST https://api.golioth.io/v1/projects/firmware_ci/devices "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff838ba190>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffff838cd370> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff8370c5f0>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'201'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Thu, 16 Oct 2025 00:39:20 GMT'), (b'x-kong-upstream-latency', b'62'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: POST https://api.golioth.io/v1/projects/firmware_ci/devices/68f03eb836dd8044fe8cfee9/credentials "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'POST']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    twister_harness.device.hardware_adapter:utils.py:37 Flashing command: /root/venv/bin/west flash --skip-rebuild --build-dir /__w/golioth-firmware-sdk/golioth-firmware-sdk/twister-out/esp32_devkitc_esp32_procpu/zephyr/hello/sample.golioth.hello.cid -- --esp-tool=/root/venv/bin/esptool.py --esp-device=/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_76b3b9235e24ed11ac32d0fff9a97352-if00-port0
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:135 Flashing finished
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:143 Opening serial connection for /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_76b3b9235e24ed11ac32d0fff9a97352-if00-port0
DEBUG    twister_harness.helpers.utils:utils.py:22 Found matching key: CONFIG_SHELL_PROMPT_UART="uart:~$ "
INFO     twister_harness.fixtures:fixtures.py:78 Wait for prompt
DEBUG    twister_harness.helpers.shell:shell.py:49 Got prompt
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff83729150>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffff838cd880> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff83729260>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'203'), (b'access-control-expose-headers', b'Content-Range'), (b'content-range', b'credentials 0-1/1'), (b'grpc-metadata-access-control-expose-headers', b'Content-Range'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Thu, 16 Oct 2025 00:39:41 GMT'), (b'x-kong-upstream-latency', b'14'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects/firmware_ci/devices/68f03eb836dd8044fe8cfee9/credentials "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [msettings set golioth/psk-id generated-UWaVsMvXjtYeAUze@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk-id to generated-UWaVsMvXjtYeAUze@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk-id saved as generated-UWaVsMvXjtYeAUze@firmware_ci
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [msettings set golioth/psk generated-UWaVsMvXjtYeAUze
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk to generated-UWaVsMvXjtYeAUze
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: Setting golioth/psk saved as generated-UWaVsMvXjtYeAUze
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [mwifi cred add -k 1 -s "***MIKES_ORANGE_PI_WIFI_SSID***" -p "***MIKES_ORANGE_PI_WIFI_PSK***"
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [mwifi cred auto_connect
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:04.524,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:04.524,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:04.525,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:05.525,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:05.527,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:06.527,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:06.529,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:07.530,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:07.532,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:08.247,000] [0m<inf> golioth_coap_client_zephyr: Golioth CoAP client connected[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:08.247,000] [0m<inf> hello_zephyr: Sending hello! 0[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:08.248,000] [0m<inf> hello_zephyr: Golioth client connected[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:08.248,000] [0m<inf> golioth_coap_client_zephyr: Entering CoAP I/O loop[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:08.537,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:08.541,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:09.541,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:09.543,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.549,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:10.552,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:11.553,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:11.555,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:12.560,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:12.564,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:13.248,000] [0m<inf> hello_zephyr: Sending hello! 1[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:13.564,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:13.567,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:14.568,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:14.570,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:15.575,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:15.579,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:16.579,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:16.582,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:17.587,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:17.590,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:18.248,000] [0m<inf> hello_zephyr: Sending hello! 2[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:18.590,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:18.593,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:19.593,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:19.595,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:20.600,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:20.604,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:21.604,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:21.606,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:22.611,000] [0m<inf> golioth_wifi: Connecting to stored WiFi network[0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[JConnection request failed (UNKNOWN/-1)
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[00:00:22.615,000] [1;31m<err> net_wifi_mgmt: Connection request failed
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [0m
DEBUG    twister_harness.device.device_adapter:device_adapter.py:150 #: [1;32muart:~$ [m[8D[J[1;32muart:~$ [m[8D[J[00:00:23.248,000] [0m<inf> hello_zephyr: Sending hello! 3[0m
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff838de050>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffff838ce690> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff838ddf50>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'access-control-expose-headers', b'Content-Range'), (b'content-range', b'logs 0-38/38'), (b'grpc-metadata-access-control-expose-headers', b'Content-Range'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Thu, 16 Oct 2025 00:40:01 GMT'), (b'x-kong-upstream-latency', b'94'), (b'x-kong-proxy-latency', b'0'), (b'via', b'kong/2.5.2, 1.1 google'), (b'transfer-encoding', b'chunked')])
INFO     httpx:_client.py:1740 HTTP Request: GET https://api.golioth.io/v1/projects/firmware_ci/logs?start=2025-10-16T00%3A39%3A41.507104Z&end=2025-10-16T00%3A40%3A01.220997Z&deviceId=68f03eb836dd8044fe8cfee9 "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'GET']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete
INFO     test_sample:test_sample.py:38 Searching log messages from end to start:
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:44 ### MATCH FOUND! ---> Sending hello! 2
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:44 ### MATCH FOUND! ---> Sending hello! 1
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Connection request failed

INFO     test_sample:test_sample.py:50 Connecting to stored WiFi network
INFO     test_sample:test_sample.py:50 Entering CoAP I/O loop
INFO     test_sample:test_sample.py:50 Golioth client connected
INFO     test_sample:test_sample.py:44 ### MATCH FOUND! ---> Sending hello! 0
DEBUG    twister_harness.device.hardware_adapter:hardware_adapter.py:190 Closed serial connection for /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_76b3b9235e24ed11ac32d0fff9a97352-if00-port0
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.started host='api.golioth.io' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG    httpcore.connection:_trace.py:87 connect_tcp.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff839f1130>
DEBUG    httpcore.connection:_trace.py:87 start_tls.started ssl_context=<ssl.SSLContext object at 0xffff8381d130> server_hostname='api.golioth.io' timeout=5.0
DEBUG    httpcore.connection:_trace.py:87 start_tls.complete return_value=<httpcore._backends.trio.TrioStream object at 0xffff839f0f50>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 send_request_headers.complete
DEBUG    httpcore.http11:_trace.py:87 send_request_body.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 send_request_body.complete
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'content-type', b'application/json'), (b'content-length', b'2'), (b'grpc-metadata-content-type', b'application/grpc'), (b'date', b'Thu, 16 Oct 2025 00:40:02 GMT'), (b'x-kong-upstream-latency', b'76'), (b'x-kong-proxy-latency', b'1'), (b'via', b'kong/2.5.2, 1.1 google')])
INFO     httpx:_client.py:1740 HTTP Request: DELETE https://api.golioth.io/v1/projects/firmware_ci/devices/68f03eb836dd8044fe8cfee9 "HTTP/1.1 200 OK"
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.started request=<Request [b'DELETE']>
DEBUG    httpcore.http11:_trace.py:87 receive_response_body.complete
DEBUG    httpcore.http11:_trace.py:87 response_closed.started
DEBUG    httpcore.http11:_trace.py:87 response_closed.complete
DEBUG    httpcore.connection:_trace.py:87 close.started
DEBUG    httpcore.connection:_trace.py:87 close.complete